apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-app.yaml
  - service-web.yaml
  - deployment-web.yaml
  - deployment-worker-image.yaml
  - deployment-worker-video.yaml
  - deployment-worker-voice.yaml
  - deployment-worker-text.yaml
  - deployment-watchdog.yaml
  - hpa-web.yaml
  - hpa-worker-image.yaml
  - hpa-worker-video.yaml
  - hpa-worker-voice.yaml
  - hpa-worker-text.yaml
