apiVersion: v1
kind: Service
metadata:
  name: foldx-web
  namespace: foldx-prod
  labels:
    app.kubernetes.io/name: foldx
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: foldx
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 3000
